[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@flarenetwork/=node_modules/@flarenetwork/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=node_modules/@openzeppelin/",
]

[rpc_endpoints]
coston2 = "https://coston2-api.flare.network/ext/C/rpc"
flare = "https://flare-api.flare.network/ext/C/rpc"
