// Regenerates src/abi.ts from the Foundry build (`forge build` at the repo root first).
// The ABIs are generated, never hand-written: a signature typed by hand in a shell string is how
// this repo lost a day in v0.4 (claude/11), and the SDK is not going to repeat it.
import { readFileSync, writeFileSync } from "node:fs";
const CONTRACTS = ["MandateRegistry", "Vault", "JudgeEvm", "JudgeXrpl", "AgentRefs", "BondLens", "AnchorLog", "SpendMeter", "JudgeSumma", "SummaMeter", "MandateFacilitator"];
let out = "// GENERATED by scripts/gen-abi.mjs from the Foundry build. Do not edit.\n\n";
for (const c of CONTRACTS) {
  const j = JSON.parse(readFileSync(new URL(`../../out/${c}.sol/${c}.json`, import.meta.url)));
  const name = c[0].toLowerCase() + c.slice(1) + "Abi";
  out += `export const ${name} = ${JSON.stringify(j.abi)} as const;\n\n`;
}
writeFileSync(new URL("../src/abi.ts", import.meta.url), out);
console.log("wrote src/abi.ts:", CONTRACTS.join(", "));
